# Generated by Django 4.1.2 on 2024-03-18 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_request', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
    ]
