# Generated by Django 4.1.2 on 2024-03-18 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_request', '0002_alter_user_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'managed': False},
        ),
    ]
